Update sync-images-dockerHub-example..yml
同步 kafka

diff --git a/.github/workflows/sync-images-dockerHub-example..yml b/.github/workflows/sync-images-dockerHub-example..yml
--- a/.github/workflows/sync-images-dockerHub-example..yml
+++ b/.github/workflows/sync-images-dockerHub-example..yml
@@ -34,4 +34,77 @@ jobs:
     - name: Use Skopeo Tools Sync Image to Docker Hub
       run: |
         #!/usr/bin/env bash
-        skopeo sync   --src docker --dest docker docker.io/bitnami/kafka registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka
+        echo "skopeo copy docker://docker.io/bitnami/kafka:1.1.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:1.1.0"
+        skopeo copy docker://docker.io/bitnami/kafka:1.1.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:1.1.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:1.1.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:1.1.1"
+        skopeo copy docker://docker.io/bitnami/kafka:1.1.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:1.1.1 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:2.0.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.0.0"
+        skopeo copy docker://docker.io/bitnami/kafka:2.0.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.0.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:2.0.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.0.1"
+        skopeo copy docker://docker.io/bitnami/kafka:2.0.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.0.1 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:2.1.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.1.0"
+        skopeo copy docker://docker.io/bitnami/kafka:2.1.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.1.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:2.1.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.1.1"
+        skopeo copy docker://docker.io/bitnami/kafka:2.1.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.1.1 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:2.2.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.2.0"
+        skopeo copy docker://docker.io/bitnami/kafka:2.2.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.2.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:2.2.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.2.1"
+        skopeo copy docker://docker.io/bitnami/kafka:2.2.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.2.1 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:2.3.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.3.0"
+        skopeo copy docker://docker.io/bitnami/kafka:2.3.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.3.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:2.3.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.3.1"
+        skopeo copy docker://docker.io/bitnami/kafka:2.3.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.3.1 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:2.4.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.4.0"
+        skopeo copy docker://docker.io/bitnami/kafka:2.4.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.4.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:2.4.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.4.1"
+        skopeo copy docker://docker.io/bitnami/kafka:2.4.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.4.1 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:2.5.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.5.0"
+        skopeo copy docker://docker.io/bitnami/kafka:2.5.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.5.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:2.6.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.6.0"
+        skopeo copy docker://docker.io/bitnami/kafka:2.6.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.6.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:2.7.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.7.0"
+        skopeo copy docker://docker.io/bitnami/kafka:2.7.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.7.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:2.8.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.8.0"
+        skopeo copy docker://docker.io/bitnami/kafka:2.8.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.8.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:2.8.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.8.1"
+        skopeo copy docker://docker.io/bitnami/kafka:2.8.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:2.8.1 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.0.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.0.0"
+        skopeo copy docker://docker.io/bitnami/kafka:3.0.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.0.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.0.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.0.1"
+        skopeo copy docker://docker.io/bitnami/kafka:3.0.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.0.1 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.0.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.0.2"
+        skopeo copy docker://docker.io/bitnami/kafka:3.0.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.0.2 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.1.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.1.0"
+        skopeo copy docker://docker.io/bitnami/kafka:3.1.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.1.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.1.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.1.1"
+        skopeo copy docker://docker.io/bitnami/kafka:3.1.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.1.1 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.1.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.1.2"
+        skopeo copy docker://docker.io/bitnami/kafka:3.1.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.1.2 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.2.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.2.0"
+        skopeo copy docker://docker.io/bitnami/kafka:3.2.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.2.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.2.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.2.1"
+        skopeo copy docker://docker.io/bitnami/kafka:3.2.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.2.1 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.2.3 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.2.3"
+        skopeo copy docker://docker.io/bitnami/kafka:3.2.3 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.2.3 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.3.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.3.1"
+        skopeo copy docker://docker.io/bitnami/kafka:3.3.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.3.1 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.3.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.3.2"
+        skopeo copy docker://docker.io/bitnami/kafka:3.3.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.3.2 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.4.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.4.0"
+        skopeo copy docker://docker.io/bitnami/kafka:3.4.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.4.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.4.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.4.1"
+        skopeo copy docker://docker.io/bitnami/kafka:3.4.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.4.1 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.5.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.5.0"
+        skopeo copy docker://docker.io/bitnami/kafka:3.5.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.5.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.5.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.5.1"
+        skopeo copy docker://docker.io/bitnami/kafka:3.5.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.5.1 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.5.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.5.2"
+        skopeo copy docker://docker.io/bitnami/kafka:3.5.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.5.2 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.6.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.6.0"
+        skopeo copy docker://docker.io/bitnami/kafka:3.6.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.6.0 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.6.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.6.1"
+        skopeo copy docker://docker.io/bitnami/kafka:3.6.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.6.1 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.6.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.6.2"
+        skopeo copy docker://docker.io/bitnami/kafka:3.6.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.6.2 || echo "skopeo copy failed, current task skip"
+        echo "skopeo copy docker://docker.io/bitnami/kafka:3.7.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.7.0"
+        skopeo copy docker://docker.io/bitnami/kafka:3.7.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/bitnami_kafka:3.7.0 || echo "skopeo copy failed, current task skip"
